### ISSUE TITLE
Ionic 4, no funciono out of the box

### ISSUE THREAD

**Issue by fernandouval** [datauy/ionic-base#1]
https://dev.to/bviveksingh/using-leaflet-to-add-maps-to-your-ionic-application-335g
https://github.com/seb999/BTrackerApp
https://edupala.com/how-to-add-leaflet-map-in-ionic/

**Comment by brunosarlo** [comment]
https://github.com/Bviveksingh/leaflet-with-ionic

Ese código esta bueno.
