### ISSUE TITLE
Generar código de pestañas

### ISSUE THREAD

**Issue by fernandouval** [datauy/ionic-base#6]
Pestañas con secciones del sitio debajo, "cerca del dedo del usuario", con ícono, leyenda e interacciones.

**Comment by brunosarlo** [comment]
No se puede usar el componente ion-tabs sin tener un prefijo "tabs" o el que quieras, es por la forma en que trabaja el componente. 
Hilo del foro: https://forum.ionicframework.com/t/ionic-4-routing-without-tabs-prefix/149613/3

Hay alternativas que requieren de controlar la navegación y cuidados en la interacción con modals por ejemplo. Podemos implementar luego esa forma.
